### ISSUE TITLE
identical graphs

### ISSUE THREAD

**Issue by Neon22** [sanzgiri/covid-19#3]
Some pairs(?) of countries appear to have the exact same graphs. Is this a data error ?

Andorra, Angola
Belize, Benin, Bhutan
Bosnia-, Botswana
Brazil, Brunei
Burma, Burundi
Colombia, Congo
Denmark, Diamond Princess
Equatorial Guinea, Eritrea
Ethiopia, Fiji,
Greece, Grenada
Guinea, Guinea-bissau
Krygyzstan, Laos
Libya, Liechenstein
Luxenbourg, MS Zandaam
Malaysia, Maldives

etc...

**Comment by Neon22** [comment]
original data seems ok.
Sorry but I can't work out why its getting the previous countries data in some circumstances.

**Comment by sanzgiri** [comment]
I found the bug. If the smoothing algorithm in `prepare_cases` fails (possibly because of too few cases), the function returns an empty list and the code incorrectly uses the smoothed data for the previous country. Will push a fix shortly.

**Comment by sanzgiri** [comment]
The recent update fixes the issue. I am excluding countries with less than 10 rows in the smoothed data.
