### ISSUE TITLE
Code Aint working(Loop for all countries)

### ISSUE THREAD

**Issue by kashishminocha** [sanzgiri/covid-19#4]
for country_name, cases in countries_to_process.groupby(level='country'):
    clear_output(wait=True)
    print(f'Processing {country_name}')
    new, smoothed = prepare_cases(cases)
    if (len(smoothed) < 10):
      print(f"Skipping {country_name}, too few cases from smoothing algorithm")
      failed_countries.append(country_name)

this loop only takes the last country in account

**Comment by sanzgiri** [comment]
Hi @kashishminocha - sorry somehow I did not get notified of this issue. I am not working on this repo anymore, I have moved the notebooks to https://github.com/sanzgiri/covid-19-dashboards/tree/master/_notebooks
